name: CI

on:
  - push
  - pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 12
          - x
    name: CI Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
      - run: yarn install
      - run: yarn ci
  pack:
    name: Pack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          check-latest: true
      - run: yarn install
      - run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: package.tgz
          path: package.tgz
