name: Delivery experiment

on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 12
          - x
    name: CI node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn ci
      - uses: actions/upload-artifact@v2
        with:
          name: fork-log-n${{ matrix.node }}-${{ github.sha }}.tgz
          path: package.tgz
