name: Delivery experiment

on:
  push:
    branches:
      - master
  pull_request_target:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 12
          - x
    name: CI node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn ci
      - uses: actions/upload-artifact@v2
        with:
          name: fork-log-n${{ matrix.node }}-${{ github.sha }}.tgz
          path: package.tgz
  delivery-experimental:
    name: Delivery experimental
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # yarn set version issue
      - uses: actions/setup-node@v1
      - run: yarn install
      - run: yarn build
      - shell: pwsh
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn config set npmAuthToken "$env:NPM_TOKEN"
      - run: >
          yarn version -i 0.0.0-exp-${{ github.sha }}
      - run: yarn npm publish --tag experimental
