name: Release Experimental

on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 12
          - x
    name: CI Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn ci
  release-experimental:
    name: Release Experimental
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # yarn set version issue
      - uses: actions/setup-node@v1
      - run: yarn install
      - run: yarn build
      - shell: pwsh
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn config set npmAuthToken "$env:NPM_TOKEN"
      - run: yarn version -i 0.0.0-experimental-${{ github.sha }}
      - run: yarn npm publish --tag experimental
